twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': App
    form_themes:
        - 'form/ef_ui_form_theme.html.twig'
        - 'form/ef_ui_form_theme_department.html.twig'
    # extensions:
    #     - App\Twig\TwigExtension

when@test:
    twig:
        strict_variables: true
