twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/ef_ui_form_theme.html.twig'
        - 'form/ef_ui_form_theme_department.html.twig'

when@test:
    twig:
        strict_variables: true
