<?php

namespace App\EventListener;

use App\Entity\Organization\Employee;
use App\Repository\Organization\EmployeeRepository;
use App\Repository\Security\WebauthnCredentialRepository;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class UserSetupListener
{
    public function __construct(
        private TokenStorageInterface $tokenStorage,
        private RouterInterface $router,
        private EmployeeRepository $employeeRepository,
        private WebauthnCredentialRepository $credentialRepository
    ) {
    }

    #[AsEventListener(event: KernelEvents::REQUEST)]
    public function onKernelRequest(RequestEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        $token = $this->tokenStorage->getToken();
        if (!$token) {
            return;
        }

        $user = $token->getUser();
        if (!$user instanceof Employee) {
            return;
        }

        $currentRoute = $event->getRequest()->attributes->get('_route');
        
        // Allowed routes during setup
        $allowedRoutes = [
            'app_user_setup',
            'app_logout',
            // WebAuthn routes
            'webauthn_register_options', // Need to check actual route names generated by bundle?
            // Actually, let's allow routes starting with /user/webauthn or /login
            // But we can check route name or path
        ];

        // Check path info for WebAuthn routes and API presence
        $pathInfo = $event->getRequest()->getPathInfo();
        if (str_starts_with($pathInfo, '/user/webauthn') || str_starts_with($pathInfo, '/login') || str_starts_with($pathInfo, '/api/presence') || str_starts_with($pathInfo, '/api/mercure')) {
            return;
        }

        // If it's an AJAX request, we might want to return 403 instead of a redirect,
        // but for now, just ignoring presence APIs is enough to fix the EventSource error.
        if (in_array($currentRoute, $allowedRoutes)) {
            return;
        }

        // Check 1: Password Modified
        if (!$user->getIsPasswordModifiedByUser()) {
            $event->setResponse(new RedirectResponse($this->router->generate('app_user_setup')));
            return;
        }

        // Check 2: Passkey
        $userEntity = $this->employeeRepository->findOneByUsername($user->getUserIdentifier());
        if ($userEntity) {
            $credentials = $this->credentialRepository->findAllForUserEntity($userEntity);
            if (count($credentials) === 0) {
                $event->setResponse(new RedirectResponse($this->router->generate('app_user_setup')));
                return;
            }
        }
    }
}
